plugins {
    id 'com.android.application'
}

android {
    namespace 'com.abhaypratap.photon'
    compileSdk 35
    ndkVersion "27.0.12077973"

    defaultConfig {
        applicationId 'com.abhaypratap.photon'
        minSdk 21
        targetSdk 35

        versionCode 300
        versionName '3.0.0'

        externalNativeBuild {
            ndkBuild {
                arguments 'APP_PLATFORM=android-21'
                abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86_64'
            }
        }
    }

    buildTypes {
        debug {
            debuggable true
        }

        release {
            minifyEnabled false
        }
    }

    externalNativeBuild {
        ndkBuild {
            path 'jni/Android.mk'
        }
    }

    packaging {
        jniLibs {
            useLegacyPackaging false
        }
    }
}
